from datetime import date
from datetime import timedelta

import plone.api


TEST_USERNAMES = (
    "alice",
    "bob",
    "carol",
    "dave",
)


def _ensure_test_users(password="5upersecret!"):
    for username in TEST_USERNAMES:
        if plone.api.user.get(username=username):
            continue
        plone.api.user.create(
            username=username,
            email=f"{username}@example.com",
            password=password,
            roles=["Member"],
        )


def _seed_doodle_folders(portal, count=10):
    base = date.today()
    for idx in range(1, count + 1):
        folder_id = f"test-{idx:02d}"
        folder = getattr(portal, folder_id, None)
        if folder is None:
            folder = plone.api.content.create(
                container=portal,
                type="experimental.doodle.folder",
                id=folder_id,
                title=f"Test Doodle {idx:02d}",
                description="Generated testing content",
                body="Generated by testing GenericSetup profile.",
            )

        for option in range(1, 4):
            option_id = f"date-{option}"
            if getattr(folder, option_id, None) is not None:
                continue
            offset = (idx - 1) * 3 + option
            participants = {
                TEST_USERNAMES[(idx + option) % len(TEST_USERNAMES)],
            }
            plone.api.content.create(
                container=folder,
                type="experimental.doodle.date",
                id=option_id,
                title=f"Option {option}",
                date=base + timedelta(days=offset),
                participants=participants,
            )


def populate_testing_data(context):
    if context.readDataFile("experimental.doodle.testingdata.txt") is None:
        return

    portal = context.getSite()
    with plone.api.env.adopt_roles(["Manager"]):
        _ensure_test_users(password="5upersecret!")
        _seed_doodle_folders(portal, count=10)
